# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/rasp_pjt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/rasp_pjt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/rasp_pjt/CMakeFiles /home/pi/rasp_pjt/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/rasp_pjt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Wono_o_Bot-1.0.out

# Build rule for target.
Wono_o_Bot-1.0.out: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Wono_o_Bot-1.0.out
.PHONY : Wono_o_Bot-1.0.out

# fast build rule for target.
Wono_o_Bot-1.0.out/fast:
	$(MAKE) -f CMakeFiles/Wono_o_Bot-1.0.out.dir/build.make CMakeFiles/Wono_o_Bot-1.0.out.dir/build
.PHONY : Wono_o_Bot-1.0.out/fast

initial_set.o: initial_set.c.o

.PHONY : initial_set.o

# target to build an object file
initial_set.c.o:
	$(MAKE) -f CMakeFiles/Wono_o_Bot-1.0.out.dir/build.make CMakeFiles/Wono_o_Bot-1.0.out.dir/initial_set.c.o
.PHONY : initial_set.c.o

initial_set.i: initial_set.c.i

.PHONY : initial_set.i

# target to preprocess a source file
initial_set.c.i:
	$(MAKE) -f CMakeFiles/Wono_o_Bot-1.0.out.dir/build.make CMakeFiles/Wono_o_Bot-1.0.out.dir/initial_set.c.i
.PHONY : initial_set.c.i

initial_set.s: initial_set.c.s

.PHONY : initial_set.s

# target to generate assembly for a file
initial_set.c.s:
	$(MAKE) -f CMakeFiles/Wono_o_Bot-1.0.out.dir/build.make CMakeFiles/Wono_o_Bot-1.0.out.dir/initial_set.c.s
.PHONY : initial_set.c.s

interruption.o: interruption.c.o

.PHONY : interruption.o

# target to build an object file
interruption.c.o:
	$(MAKE) -f CMakeFiles/Wono_o_Bot-1.0.out.dir/build.make CMakeFiles/Wono_o_Bot-1.0.out.dir/interruption.c.o
.PHONY : interruption.c.o

interruption.i: interruption.c.i

.PHONY : interruption.i

# target to preprocess a source file
interruption.c.i:
	$(MAKE) -f CMakeFiles/Wono_o_Bot-1.0.out.dir/build.make CMakeFiles/Wono_o_Bot-1.0.out.dir/interruption.c.i
.PHONY : interruption.c.i

interruption.s: interruption.c.s

.PHONY : interruption.s

# target to generate assembly for a file
interruption.c.s:
	$(MAKE) -f CMakeFiles/Wono_o_Bot-1.0.out.dir/build.make CMakeFiles/Wono_o_Bot-1.0.out.dir/interruption.c.s
.PHONY : interruption.c.s

main.o: main.c.o

.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) -f CMakeFiles/Wono_o_Bot-1.0.out.dir/build.make CMakeFiles/Wono_o_Bot-1.0.out.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i

.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) -f CMakeFiles/Wono_o_Bot-1.0.out.dir/build.make CMakeFiles/Wono_o_Bot-1.0.out.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s

.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) -f CMakeFiles/Wono_o_Bot-1.0.out.dir/build.make CMakeFiles/Wono_o_Bot-1.0.out.dir/main.c.s
.PHONY : main.c.s

motion.o: motion.c.o

.PHONY : motion.o

# target to build an object file
motion.c.o:
	$(MAKE) -f CMakeFiles/Wono_o_Bot-1.0.out.dir/build.make CMakeFiles/Wono_o_Bot-1.0.out.dir/motion.c.o
.PHONY : motion.c.o

motion.i: motion.c.i

.PHONY : motion.i

# target to preprocess a source file
motion.c.i:
	$(MAKE) -f CMakeFiles/Wono_o_Bot-1.0.out.dir/build.make CMakeFiles/Wono_o_Bot-1.0.out.dir/motion.c.i
.PHONY : motion.c.i

motion.s: motion.c.s

.PHONY : motion.s

# target to generate assembly for a file
motion.c.s:
	$(MAKE) -f CMakeFiles/Wono_o_Bot-1.0.out.dir/build.make CMakeFiles/Wono_o_Bot-1.0.out.dir/motion.c.s
.PHONY : motion.c.s

sensor.o: sensor.c.o

.PHONY : sensor.o

# target to build an object file
sensor.c.o:
	$(MAKE) -f CMakeFiles/Wono_o_Bot-1.0.out.dir/build.make CMakeFiles/Wono_o_Bot-1.0.out.dir/sensor.c.o
.PHONY : sensor.c.o

sensor.i: sensor.c.i

.PHONY : sensor.i

# target to preprocess a source file
sensor.c.i:
	$(MAKE) -f CMakeFiles/Wono_o_Bot-1.0.out.dir/build.make CMakeFiles/Wono_o_Bot-1.0.out.dir/sensor.c.i
.PHONY : sensor.c.i

sensor.s: sensor.c.s

.PHONY : sensor.s

# target to generate assembly for a file
sensor.c.s:
	$(MAKE) -f CMakeFiles/Wono_o_Bot-1.0.out.dir/build.make CMakeFiles/Wono_o_Bot-1.0.out.dir/sensor.c.s
.PHONY : sensor.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Wono_o_Bot-1.0.out"
	@echo "... edit_cache"
	@echo "... initial_set.o"
	@echo "... initial_set.i"
	@echo "... initial_set.s"
	@echo "... interruption.o"
	@echo "... interruption.i"
	@echo "... interruption.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... motion.o"
	@echo "... motion.i"
	@echo "... motion.s"
	@echo "... sensor.o"
	@echo "... sensor.i"
	@echo "... sensor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

